FROM alpine
RUN apk add --no-cache \
	bash \
	bison \
	ccache \
	clang \
	clang-extra-tools \
	cmake \
	curl \
	flex \
	g++ \
	git \
	ninja \
	python3 \
	unzip \
	zlib-dev
RUN ln -s /usr/bin/python3 /usr/local/bin/python

ADD https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py /usr/local/bin/run-clang-format
RUN chmod +x /usr/local/bin/run-clang-format
