FROM alpine:latest
RUN apk add --no-cache \
    binutils \
    curl \
    git \
    patchelf \
    tzdata \
    unzip

RUN cp /usr/share/zoneinfo/Australia/Melbourne /etc/localtime
RUN echo "Australia/Melbourne" > /etc/timezone
RUN apk del tzdata